### ISSUE TITLE
Graphe Vertical: Repartition Mensuelle

### ISSUE THREAD

**Issue by Moobster** [INTMSNCF/tickets-dashboard#61] opened 2021-02-03 13:58 UTC

**Comment by Moobster** [comment] 2021-02-03 13:58
![repartition annuelle](https://user-images.githubusercontent.com/45401704/106757171-55dde180-6630-11eb-93ba-b3fa6d5e3bda.PNG)

**Comment by Moobster** [comment] 2021-02-03 13:59
Comme la repartition annuelle mais mensuelle

**Comment by alograg** [comment] 2021-02-08 09:23
Duplicate of #60

**Closed as completed by alograg** 2021-02-08 09:23 UTC
Labels: duplicate, enhancement
